apiVersion: v1
kind: Pod
metadata:
  name: trie-client-pod
spec:
  containers:
    - name: trie-client
      image: localhost/trie-client:v1
      imagePullPolicy: Never
      stdin: true
      tty: true
      command: ["/bin/sh", "-c", "sleep infinity"]