apiVersion: v1
kind: Service
metadata:
  name: trie-server-service
spec:
  selector:
    app: trie-server
  ports:
    - protocol: TCP
      port: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trie-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trie-server
  template:
    metadata:
      labels:
        app: trie-server
    spec:
      containers:
        - name: trie-server
          image: localhost/trie-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051

---
apiVersion: v1
kind: Pod
metadata:
  name: trie-client-pod
spec:
  containers:
    - name: trie-client
      image: localhost/trie-client:v3
      imagePullPolicy: Never
      stdin: true
      tty: true
      command: ["/bin/sh", "-c", "sleep infinity"]
